seed: 0

env:
  max_steps: 100
  scenario_name: "waterfall"
  scenario:
    n_agents: 3
  device: ???
  num_envs: ???

model:
  shared_parameters: False
  centralised: True
  depth: 2
  num_cell: 64

collector:
  frames_per_batch: 60_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.9
  tau: 0.005 # For target net

curiosity:
  encoding_size: 8

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 4096 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  enable: False
  backend:  wandb 