seed: 0

env:
  max_steps: 1000
  frame_skip: 1
  env_name: "Ant-v4"
  from_pixels: False
  kwargs:
    terminate_when_unhealthy: True

model:
  depth: 3
  num_cell: 128

collector:
  frames_per_batch: 2048
   # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.99
  lmbda: 0.95
  tau: 0.005 # For target net

curiosity:
  encoding_size: 64
  beta: 0.2
  eta: 0.05
  intrinsic_only: False

train:
  num_epochs: 30  # optimization steps per batch of data collected
  minibatch_size: 256 # size of minibatches used in each epoch
  lr: 0.0001
  decay: 0.0 
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  enable: True
  backend:  wandb 